# Generated by Django 3.0 on 2021-11-28 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDentalCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseTitle', models.CharField(max_length=10)),
                ('MdcPinNumber', models.IntegerField(blank=True, null=True)),
                ('CertificateNumber', models.IntegerField(blank=True, null=True)),
                ('DateOfCompletion', models.DateField(blank=True, null=True)),
                ('EntryTime', models.TimeField(auto_now_add=True)),
                ('EntryDate', models.DateField(auto_now_add=True)),
                ('Course', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=20, null=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
