# Generated by Django 3.0 on 2021-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDentalCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, verbose_name='user-name')),
                ('CourseTitle', models.CharField(max_length=10)),
                ('MdcPinNumber', models.IntegerField(blank=True, null=True)),
                ('CertificateNumber', models.IntegerField(blank=True, null=True)),
                ('DateOfCompletion', models.DateField(blank=True, null=True)),
                ('Type', models.CharField(max_length=100, verbose_name='Type')),
                ('EntryTime', models.TimeField(auto_now_add=True)),
                ('EntryDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
