# Generated by Django 3.0 on 2021-11-28 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalanddental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldentalcouncil',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
