# Generated by Django 3.0 on 2021-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalanddental', '0002_auto_20211129_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldentalcouncil',
            name='Course',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldentalcouncil',
            name='Username',
            field=models.CharField(max_length=15),
        ),
    ]
